CORE_REPOSITORY=https://github.com/shtorm-7/sing-box-extended.git
CORE_TAG=v1.13.14-extended-2.5.2
CORE_COMMIT=ff11f007ec798136a5de258f947a4f34011a37ea
CORE_PATCH_FILE=core-patches/0001-android-disable-wireguard-endpoint-roaming.patch
CORE_PATCH_SHA256=715e79e0b03d499be36dc5dbb8ee5b10b3138a0dbaea338c11c911a02f7fb171
GO_VERSION=1.26.4
GOMOBILE_VERSION=v0.1.12
ANDROID_NDK_VERSION=28.0.13004108
ANDROID_COMPILE_SDK=36
ANDROID_BUILD_TOOLS=36.0.0
